name: Typecheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn tsc
